version: '2'

services:
  blog-server:
    build: ./provisioning
    image: laravel-blog
    links:
      - mysql
    volumes:
      - ./:/application

  queue-server:
    build: .
    image: laravel-blog
    command: php artisan queue:work
    links:
      - mysql
    volumes:
      - ./:/application

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - ./storage/tmp/db:/var/lib/mysql

  mysql-test:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing
    volumes:
      - ./storage/tmp/test:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    links:
      - blog-server
